import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { safeLocalStorage } from '../utils/storage';

export type Language = 'sw' | 'en';

type TranslationKey = string;

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  sw: {
    // Nav & Sidebar Tabs
    'nav.dashboard': 'Dashboard',
    'nav.eventDetails': 'Tukio (Event Details)',
    'nav.preview': 'Uhakiki (Preview)',
    'nav.templates': 'Templates',
    'nav.guests': 'Wageni (Upload Guests)',
    'nav.send': 'Tuma (Send)',
    'nav.rsvp': 'RSVP Responses',
    'nav.contributions': 'Michango',
    'nav.scan': 'Skani (Scan QR)',
    'nav.settings': 'Akaunti (Settings)',
    'nav.wallet': 'Kijipochi (Wallet)',
    'nav.logout': 'Kutoka (Log Out)',
    'nav.adminPortal': 'PORTAL YA USIMAMIZI',
    'nav.account': 'Akaunti',
    'nav.username': 'Mwenyeji',
    'nav.active': 'Active',
    'nav.otpSkipped': 'Uthibitisho wa OTP: Umerukwa',
    'nav.pricingSkipped': 'Malipo: Yamerukwa',

    // Landing Page
    'landing.title1': 'Tengeneza na Utume Kadi za Mialiko kwa',
    'landing.title2': 'Dakika Chache',
    'landing.subtitle': 'Tuma mwaliko wa matukio yako (Harusi, Send-off, Kipaimara, n.k.) kwa njia salama na rahisi kupitia WhatsApp au SMS, kufuatilia majibu (RSVP), na kukagua wageni mlangoni kupitia QR Code.',
    'landing.btnStart': 'Anza Kutengeneza Tukio',
    'landing.btnHowItWorks': 'Angalia Jinsi Inavyofanya Kazi',
    'landing.btnStartNow': 'Anza Sasa',
    'landing.btnLogin': 'Ingia (Login)',
    'landing.inviteTag': 'Kadi za Mialiko ya Kidijitali',
    'landing.statSent': 'Kadi Zilitumwa',
    'landing.statRsvped': 'Wageni Walijibu RSVP',
    'landing.statSavePaper': 'Karatasi Iliyopotea',
    'landing.featuresTitle': 'Faida za Kipekee',
    'landing.featuresHeading': 'Zana Zote za Kusimamia Wageni Sehemu Moja Salama',
    'landing.featuresSub': 'Sema kwa heri mialiko ya zamani ya karatasi na ujisumbue na gharama zisizo na msingi. EVENTCARD hukupa teknolojia ya kisasa na rahisi.',
    'landing.howItWorksTitle': 'Rahisi na Wazi',
    'landing.howItWorksHeading': 'Hatua Kubwa Nne Tu za Kumaliza Sherehe Yako',
    'landing.howItWorksSub': 'Mfumo huu umebuniwa kukupa wepesi wa kiwango cha juu. Hapa kuna muhtasari mzuri wa unavyoanza mpaka siku ya tukio.',
    'landing.faqTitle': 'Maswali ya Kawaida (FAQs)',
    'landing.faqSub': 'Tunazo majibu kwa maswali unayoweza kuwa nayo kuhusu mfumo wetu.',
    'landing.tagline': 'Uvumbuzi, wepesi na ukamilifu mmoja wa mialiko ya kidijitali nchini Tanzania.',
    'landing.rights': 'EVENTCARD. Haki zote zimehifadhiwa. Imeundwa kwa kiwango cha juu cha kidijitali.',

    // Feature Cards
    'feature.1.title': '1. Uundaji wa Kadi za Kisasa',
    'feature.1.desc': 'Chagua template au weka picha yako. Unaweza kusogeza eneo la jina la mgeni, aina ya kadi, na QR code sehemu yoyote unayotaka juu ya picha ili kukaa vizuri.',
    'feature.2.title': '2. Tuma Kupitia WhatsApp & SMS',
    'feature.2.desc': 'Tuma mwaliko kwa njia salama na muundo unaovutia sana. Wageni hupokea meseji ikiwa na jina lao, maelekezo ya ukumbi, na picha yao maalum ya kadi.',
    'feature.3.title': '3. Ufuatiliaji wa RSVP wa Wakati Halisi',
    'feature.3.desc': 'Pata taarifa za papo hapo wageni wakithibitisha kuhudhuria, kukataa, au wasipokuwa na uhakika (RSVP) kupitia dashboard yako. Rahisisha makadirio ya chakula na vinywaji.',
    'feature.4.title': '4. Uhakiki wa Mlangoni (QR Scanner)',
    'feature.4.desc': 'Siku ya sherehe, mkataba mlangoni atatumia tu kamera ya simu kuskani kadi ya mgeni. Anasaidia kuzuia watu wasioalikwa, kudhibiti kadi feki, au matukio ya mara mbili.',
    'feature.5.title': '5. Hakuna Makaratasi au Upotevu',
    'feature.5.desc': 'Kuwa mstaarabu na utunze mazingira! Wageni wanajisikia faraja kupokea kadi ya mwaliko safi ya kidijitali bila hofu ya kuipoteza au kusahau nyumbani.',

    // Steps
    'step.1.title': 'Andaa Taarifa za Tukio',
    'step.1.desc': 'Weka jina la tukio (mf. Sendoff), mahali, saa, tarehe, dress code, na namba zako tatu za mawasiliano ya kupokea simu.',
    'step.2.title': 'Hifadhi na preview templates',
    'step.2.desc': 'Fanya uhakiki (Preview) wa kadi na ubadilishe position ya majina, code ya QR n.k. (Kipengele cha Pricing kimerukwa kabisa).',
    'step.3.title': 'Pakia Wageni wako',
    'step.3.desc': 'Ongeza mgeni kwa mgeni au uweke wote kwa wingi. Kadi maalum yenye jina la mgeni na QR Code yake itaundwa hapohapo bure.',
    'step.4.title': 'Tuma na kufatilia RSVPs',
    'step.4.desc': 'Tuma salama kupitia WhatsApp na SMS. Siku ya event tumia QR Scanner mlangoni kudhibiti mwaliko wa dhati.',

    // FAQ Content
    'faq.1.q': 'Je, inapaswa kusubiri OTP wakati wa kujisajili?',
    'faq.1.a': 'Hapana, kwa matoleo haya maalum tumeweza kuondoa kipengele cha kuweka OTP mwanzo. Unaingia sasa hivi kwa namba ya jina la admin na nenosiri admin ili kupata uwezo wa kila kitu.',
    'faq.2.q': 'Je, tunaweza kulipia nini? Kushinda "Pricing" kumerukwa?',
    'faq.2.a': 'Imekaa vizuri sana! Kipengele cha Pricing kimenusurika kulingana na muundo tuliochagua. Ukishamaliza kutengeneza tukio, unaenda moja kwa moja kwenda kuhariri templates bila mzunguko wowote au mahitaji ya malipo.',
    'faq.3.q': 'Je! Wageni wangu wanapitia tovuti gani kujaza RSVP?',
    'faq.3.a': 'Mfumo wetu unampa kila mgeni linki ya mwaliko wa kipekee kwa upande wao. Wakibofya, wanatambuliwa kwa majina yao, wanaona kadi yao yenye QR Code yao na kuchagua "Nitafika" au "Sitaweza" kufika. Taarifa hii imesasishwa kwa ukamilifu haraka kwenye admin dashboard yako dhabiti.',

    // Admin Dashboard Info Panel
    'dash.welcome': 'Karibu EVENTCARD Dashboard',
    'dash.intro': 'Hapa kuna orodha na takwimu za jumla za mialiko yako ya kidijitali. Kipengele cha kuweka OTP mwanzo kimefutwa kabisa sasa hivi na una uwezo wa moja kwa moja. Hatua ya Pricing kimerukwa pia, hivyo unaingiza taarifa za kadi yako, unaviona mbele ya screen (Preview) na kuendelea kuteka kadi moja kwa moja.',
    'dash.btnCreateEvent': 'Tengeneza Tukio',
    'dash.statEventName': 'Tukio Lako Halisi',
    'dash.statGuestsLoaded': 'Wageni Waliopakiwa',
    'dash.statRsvps': 'Waliojibu RSVP',
    'dash.statWallet': 'Mkoba (Wallet Credit)',
    'dash.workflowTitle': 'Njia ya Kutengeneza (System Workflow)',
    'dash.wf1Title': 'Weka Taarifa za Tukio',
    'dash.wf1Desc': 'Andika kichwa cha sherehe, muda, mavazi na masharti.',
    'dash.wf2Title': 'Hakiki Meseji zao (Preview)',
    'dash.wf2Desc': 'Kagua SMS na WhatsApp templates na kuruka Pricing moja kwa moja.',
    'dash.wf3Title': 'Panga Template na positions',
    'dash.wf3Desc': 'Sogeza eneo la jina la mgeni na QR code kukaa vizuri ya canva.',
    'dash.wf4Title': 'Pakia Wageni & Sambaza',
    'dash.wf4Desc': 'Kamilisha kwa SMS na sani wageni wote mlangoni siku ya event.',
    'dash.summaryCardTitle': 'Muhtasari wa Sherehe Ilondaliwa',
    'dash.summaryCardName': 'Jina la Sherehe:',
    'dash.summaryCardDateTime': 'Siku na Saa:',
    'dash.summaryCardHall': 'Jengo:',
    'dash.summaryCardHosts': 'Wakaribishaji:',
    'dash.summaryCardDress': 'Dress Code:',
    'dash.btnEditInfo': 'Hariri Taarifa hizi',
    'dash.btnDesignCard': 'Sanifu Kadi Sasa',

    // Event Details Form
    'form.title': 'Taarifa Kuu za Sherehe (Event Coordinates Setup)',
    'form.subtitle': 'Weka taarifa rasmi za sherehe yako. Taarifa hizi zitatumika kutengeneza kadi na kuandika meseji za mwaliko kamilifu.',
    'form.sec1': 'A: Mawasiliano ya Mwasilishaji (Sender Metadata)',
    'form.sec2': 'B: Ratiba na Eneo la Sherehe (Date & Venue Details)',
    'form.sec3': 'C: Wakaribishaji na Mavazi (Hosts & Dress Code)',
    'form.sec4': 'D: Nambari za Simu za Kujibu (RSVP Contact Lines)',
    'form.labelSender': 'Kichwa cha Meseji / SMS Sender ID',
    'form.labelEventName': 'Jina Kamili la Sherehe (e.g. SEND OFF YA DIANA)',
    'form.labelDate': 'Tarehe ya Sherehe',
    'form.labelTime': 'Muda wa Kuanza',
    'form.labelPeriod': 'Kipindi cha Siku',
    'form.labelHall': 'Jina la Ukumbi / Hall Name',
    'form.labelCoordinates': 'Ramani (Google Maps Coordinates - Latitude, Longitude)',
    'form.labelHosts': 'Wakaribishaji Wakuu (e.g. Familia ya Rev. Fidelis)',
    'form.labelDress': 'Aina ya Mavazi (Dress Code)',
    'form.labelContact1': 'Namba ya Kamati 1 (RSVP)',
    'form.labelContact2': 'Namba ya Kamati 2 (RSVP)',
    'form.labelContact3': 'Namba ya Kamati 3 (RSVP)',
    'form.labelEventCover': 'Picha ya Jalada la Tukio (Event Cover)',
    'form.labelSaveDateImg': 'Picha ya Save the Date (Meseji ya Ukumbusho)',
    'form.eventCoverHint': 'Pakia picha nzuri itakayoonekana mwanzo wa mwaliko kwa mgeni.',
    'form.saveDateHint': 'Pakia picha itakayotumwa kama ukumbusho (Save the Date).',
    'form.btnUpload': 'Pakia Picha',
    'form.btnChange': 'Badilisha Picha',
    'form.btnSave': 'Hifadhi Taarifa za Tukio ✓',

    // Card Preview Page
    'preview.title': 'Uhakiki wa Meseji ya Mwaliko (Message Template Review)',
    'preview.subtitle': 'Kipengele hiki cha msimbo kinaruka Pricing hatua yote! Unaweza kuhakiki meseji zitakazotumwa kwa SMS na WhatsApp kielektroniki kwa wageni.',
    'preview.smsTitle': 'Aina ya Kwanza: Hakiki Muundo wa SMS (SMS Template Preview)',
    'preview.whatsTitle': 'Aina ya Pili: Hakiki Muundo wa WhatsApp (WhatsApp Template Review)',
    'preview.priceAlert': 'Ilani ya Maana: Pricing kimerukwa. Hatua inayofuata ni kusogeza template elements moja kwa moja.',
    'preview.btnNext': 'Nenda Kwenye Templates selectors',

    // Templates Selector
    'temp.title': 'Kadi Template na Mpangilio (Template Settings)',
    'temp.subtitle': 'Sanifu mwonekano wa kadi kwa kuchagua presets na kusogeza maeneo ya majina pamoja na QR Codes.',
    'temp.presetTitle': '1. Chagua Rangi & Uhusika wa Kadi (Card Presets)',
    'temp.positionTitle': '2. Mpangilio wa Vipengele (Position Settings)',
    'temp.activeSection': 'Hariri Eneo',
    'temp.tabName': 'Jina la Mgeni',
    'temp.tabQr': 'QR Code Position',
    'temp.tabType': 'Aina ya Kadi',
    'temp.nameSliderHeader': 'Uhariri wa eneo la Jina la Mgeni',
    'temp.nameX': 'Upana wa Kushoto (X Position)',
    'temp.nameY': 'Urefu wa Kwenda Juu/Chini (Y Position)',
    'temp.nameSize': 'Ukubwa wa Fonti (Font Size)',
    'temp.qrSliderHeader': 'Uhariri wa eneo la Kisimbuzi cha QR (QR Code)',
    'temp.qrX': 'Msimamo wa Kushoto/Kulia (X Position)',
    'temp.qrY': 'Msimamo wa Juu/Chini (Y Position)',
    'temp.qrSize': 'Ukubwa wa QR Code Square (Size)',
    'temp.typeSliderHeader': 'Uhariri wa eneo la Aina ya Kadi (Card Type Badge)',
    'temp.typeX': 'Msimamo wa Kushoto/Kulia (X Position)',
    'temp.typeY': 'Msimamo wa Juu/Chini (Y Position)',
    'temp.typeSize': 'Ukubwa wa Font (Size)',
    'temp.textColorLabel': 'Rangi ya Maandishi (Text Tone)',
    'temp.fontFamilyLabel': 'Aina ya Fonti (Font Family)',
    'temp.btnSave': 'Hifadhi Mipangilio ✓',
    'temp.btnSaved': 'Imehifadhiwa!',
    'temp.btnNext': 'Weka Wageni (Upload Guests)',
    'temp.canvasHeader': '3. Live Canva Preview (450 x 600 px)',
    'temp.canvasSub': 'Huu ndio mwonekano halisi wa kadi watakayoihifadhi wageni kwa PDF/Picha ikiwa na nambari yao mahususi ya QR kulingana na kundi lao.',

    // Upload Guests
    'guests.title': 'Pakia Orodha ya Wageni (Guest Directory Setup)',
    'guests.subtitle': 'Ongeza majina ya wageni hapa chini. Mfumo utazalisha kadi yenye QR Code maalum tanzu kwa kiwango chochote kile dharura.',
    'guests.formHeader': 'Ongeza Mwalikwa Mmoja kwa Moja (Single Guest Insert)',
    'guests.labelFullName': 'Jina Kamili la Mgeni',
    'guests.labelPhone': 'Nambari ya Simu (e.g. 0714786751)',
    'guests.labelCardType': 'Aina ya Kadi (Card Category)',
    'guests.btnAdd': 'Ongeza Kwenye Orodha +',
    'guests.bulkHeader': 'Pakia Wageni kwa Wingi (Bulk Paste / Excel Upload Simulation)',
    'guests.bulkDesc': 'Ingiza majina na namba kwa muundo ufuatao (kila mstari ubebe Jina na Simu, zikitenganishwa na koma au tab):',
    'guests.bulkPlaceholder': 'Mfano:\nJina la Mgeni, Nambari ya Simu, AINA\nJina la Kwanza, 0713111222, DOUBLE\nJina la Pili, 0755333444, SINGLE',
    'guests.btnBulk': 'Pakia Wageni Wote ✓',
    'guests.tableHeader': 'Orodha ya Wageni Walioingizwa (Guests Registry)',
    'guests.thName': 'Jina Kamili la Mgeni',
    'guests.thPhone': 'Phone',
    'guests.thCard': 'Aina ya Kadi',
    'guests.thStatus': 'Hali ya Usafirishaji',
    'guests.thAction': 'Zana',
    'guests.btnSms': 'Bado SMS',
    'guests.btnWhatsapp': 'Bado WhatsApp',
    'guests.btnDelete': 'Futa',
    'guests.noData': 'Bado hujaongeza wageni wowote. Tumia fomu zilizo hapo juu kuongeza.',
    'guests.btnDemo': '',
    'guests.btnNext': 'Endelea Kutuma Kadi (Proceed to Delivery)',

    // Send Messages
    'send.title': 'Kusambaza Kadi za Mialiko (Dispatch & Message Logs)',
    'send.subtitle': 'Tuma mialiko yote ya kidijitali kwa njia ya kipekee. Unaweza kufuatilia hali ya uwasilishaji kwa SMS na WhatsApp kwenye jedwali hapa chini.',
    'send.btnSmsAll': 'Tuma SMS kwa Wageni Wote',
    'send.btnWhatsappAll': 'Tuma WhatsApp kwa Wageni Wote',
    'send.thName': 'Jina la Mwalikwa (Guest Name)',
    'send.thPhone': 'Mawasiliano',
    'send.thSmsStatus': 'SMS Dispatch',
    'send.thWhatStatus': 'WhatsApp Dispatch',
    'send.thActions': 'Tuma Mmoja mmoja',
    'send.noGuests': 'Hakuna wageni waliopatikana kwa ajili ya kutumiwa kadi.',
    'send.smsStatusOk': 'Imetumia',
    'send.smsStatusSending': 'Inatuma',
    'send.smsStatusPending': 'Sijatuma',
    'send.btnSmsSingle': 'Tuma SMS',
    'send.btnWhatSingle': 'Tuma WhatsApp',
    'send.btnNext': 'Ufuatiliaji wa Majibu (RSVP Portal)',

    // RSVP Responses
    'rsvp.title': 'Mrejesho wa Mwaliko (RSVP Responses)',
    'rsvp.subtitle': 'Angalia takwimu, idadi ya wageni wanaokuja, na ujumbe wa pongezi walioandika wageni.',
    'rsvp.btnDemo': 'Simulate Majibu ya Wageni (Demo Click)',
    'rsvp.statAttending': 'Wanakuja (Attending)',
    'rsvp.statDeclined': 'Hawaji (Declined)',
    'rsvp.statMaybe': 'Hawana Uhakika',
    'rsvp.statPending': 'Bado Kujibu',
    'rsvp.chartTitle': 'Chati ya Mrejesho (RSVP Attendance Analytics)',
    'rsvp.chartAttending': 'WATAKAO HUDHURIA',
    'rsvp.chartDeclined': 'HAWATAWEZA KUJA',
    'rsvp.chartPending': 'BADO KUJIBU MREJESHO',
    'rsvp.tableTitle': 'Mwalikwa (Guest Name)',
    'rsvp.thPhone': 'Phone',
    'rsvp.thStatus': 'RSVP Status',
    'rsvp.thCount': 'Wageni wanaokuja',
    'rsvp.thComment': 'Kumbukumbu / Maoni ya pongezi',
    'rsvp.thActions': 'Zana / Hali',
    'rsvp.btnSim': 'Jaribu RSVP (Simulate)',
    'rsvp.noGuests': 'Hakuna wageni waliopatikana kwa ajili ya kufuatilia RSVP.',
    'rsvp.btnNext': 'Uhakiki wa Mlangoni (QR Scanner)',

    // RSVP Guest Simulator Dialog
    'sim.badge': 'Simulator: Muonekano upande wa Simu ya Mgeni',
    'sim.webTitle': 'TOVUTI BINAFSI YA MWALIKO (RSVP LINK)',
    'sim.welcomeMsg': 'Karibu sana kujibu mwaliko wa sherehe sasa.',
    'sim.qAttendance': 'Je, utahudhuria sherehe hii ya mwaliko?',
    'sim.btnAttending': '✓ Nitafika',
    'sim.btnDeclined': '✕ Sitaweza',
    'sim.btnMaybe': '? Labda',
    'sim.qCompanions': 'Umekuja na wenza wangapi kuhifadhi siti?',
    'sim.opt1': 'Mimi peke yangu (Siti 1)',
    'sim.opt2': 'Nitafika na Mwenza wangu (Siti 2)',
    'sim.opt3': 'Watatu (Siti 3)',
    'sim.qComment': 'Ujumbe maalum wa Pongezi kwa Waandaji (Pongezi/Ombi)',
    'sim.commentPlaceholder': 'e.g. Hongereni sana, nitakuja kufanikisha sherehe hii!',
    'sim.btnSubmit': 'Wasilisha Mrejesho RSVP ✓',

    // QR Check-in
    'scan.title': 'Kagua Wageni Mlangoni (QR Scanner & Check-in)',
    'scan.subtitle': 'Kurasa ya kukaribisha wageni. Skani kadi namba ya QR kuzuia uingiaji haramu siku ya tukio au kagua kwa majina.',
    'scan.tabQr': 'Skani QR Code',
    'scan.tabList': 'Orodha Walioingia',
    'scan.scannerActive': 'KADU SCANNER ACTIVE',
    'scan.waiting': 'Inasubiri kuskani kadi...',
    'scan.scanOkTitle': 'Mgeni Amekubaliwa!',
    'scan.scanDupTitle': 'Kadi Ishatumiwa!',
    'scan.scanWarn': '*Onyo: Kadi hii haiwezi kuingia mara mbili!',
    'scan.scanFailTitle': 'Kadi Feki / Batili!',
    'scan.scanFailText': 'Nambari ya QR haikutambulika au mwaliko huu si halali kwa sherehe hii.',
    'scan.simBoxTitle': 'Simulate / Jaribu QR Code Scan (Mlangoni)',
    'scan.simBoxDesc': 'Ili kuiga kitendo cha skani kadi mlangoni, chagua mgeni yeyote kutoka kwenye orodha hapa chini, kisha bofya "Skani Kadi". Mfumo utasoma QR ya mgeni huyo na kurekodi takwimu za uingiaji.',
    'scan.dropdownLabel': 'Hariri: Chagua Mgeni wa Kuskani',
    'scan.btnSubmit': 'Kamilisha Skani ya QR sasa',
    'scan.statChecked': 'Walioingia (Checked In)',
    'scan.statRsvped': 'Waliothibitisha RSVP',
    'scan.tblHeader': 'Orodha Walioingia',
    'scan.thName': 'Jina Kamili la Mgeni',
    'scan.thPhone': 'Phone',
    'scan.thCard': 'Aina ya Kadi',
    'scan.thTime': 'Checked-in Time',
    'scan.thVerify': 'Uhakiki',
    'scan.noCheckedIn': 'Hakuna mgeni aliyeingia bado. Anza kuskani kadi kurahisisha kazi!',

    // Settings Form
    'sett.title': 'Mipangilio ya Akaunti (Account Settings)',
    'sett.labelName': 'Jina Kamili la Msimamizi',
    'sett.labelEmail': 'Barua Pepe (Email Address)',
    'sett.labelPhone': 'Namba ya Simu kuu',
    'sett.labelFont': 'Badilisha Fonti ya Mfumo (System Font Selection)',
    'sett.fontDesc': 'Chagua muonekano wa herufi kwa mfumo mzima wa EVENTCARD. Mabadiliko yatatumika papo hapo kwenye kurasa zote.',
    'sett.btnSave': 'Hifadhi Wasifu Wangu ✓',
    'sett.alertSaved': 'Profile imehifadhiwa!',

    // Wallet Page
    'wallet.title': 'Mkoba na Salio (Wallet Account)',
    'wallet.typePrepaid': 'EVENTCARD PREPAID WORKSPACE',
    'wallet.totalBal': 'Salio lililopo (Total Balance)',
    'wallet.tagActive': 'Active',
    'wallet.tagUnlimited': 'Muda: Unlimited',
    'wallet.rechargeTitle': 'Ongeza Salio Mfano (Simulated Wallet Deposit)',
    'wallet.rechargeDesc': 'Ongeza salio kwenye akaunti ya dema afinishi ili usisumbuliwe na hitaji la kifurushi, upige mtihani wa kutuma SMS kwa ufasaha.',
    'wallet.rechargeSelect': 'Chagua Kiasi cha Kuongeza',
    'wallet.btnRecharge': 'Weka Salio Sasa',
    'wallet.rechargeSuccess': 'Zimeongezwa kwenye mkoba wako kwa simulizi!',
    'wallet.tblHistory': 'Historia ya Miamala (Transaction History)',
    'wallet.thDate': 'Tarehe',
    'wallet.thDesc': 'Maelezo (Transaction)',
    'wallet.thType': 'Dhahama',
    'wallet.thAmount': 'Kiasi (Amount)',
    'wallet.typeIn': 'WEKA',
    'wallet.typeOut': 'KUTOA',
    'wallet.depositDesc': 'Simulated Deposit AirtelMoney',
    'wallet.purchaseDesc': 'SMS Pack Purchase (1000 SMS)',

    // Login page
    'login.title': 'Ingia Kwenye Jopo la EVENTCARD',
    'login.sub': 'Usimamizi wa Kadi za Mialiko ya Kidijitali ya EVENTCARD',
    'login.note': 'Mwasilishaji Maalum: Tumia admin kama jina la mtumiaji na nenosiri kuanza kazi moja kwa moja.',
    'login.username': 'Jina la Mtumiaji (Username)',
    'login.password': 'Nenosiri (Password)',
    'login.btnSubmit': 'Ingia Salama Kwenye Mfumo ✓',
    'login.btnBack': '← Rudi Mwanzo',
  },
  en: {
    // Nav & Sidebar Tabs
    'nav.dashboard': 'Dashboard',
    'nav.eventDetails': 'Event Details',
    'nav.preview': 'Preview Message',
    'nav.templates': 'Card Templates',
    'nav.guests': 'Upload Guests',
    'nav.send': 'Send Invitations',
    'nav.rsvp': 'RSVP Responses',
    'nav.contributions': 'Contributions',
    'nav.scan': 'QR Check-In',
    'nav.settings': 'Account Settings',
    'nav.wallet': 'Prepaid Wallet',
    'nav.logout': 'Log Out',
    'nav.adminPortal': 'ADMINISTRATOR PORTAL',
    'nav.account': 'Account',
    'nav.username': 'Host',
    'nav.active': 'Active',
    'nav.otpSkipped': 'OTP Verification: Skipped',
    'nav.pricingSkipped': 'Pricing Page: Skipped',

    // Landing Page
    'landing.title1': 'Create & Send Elegant Digital Invitation Cards in',
    'landing.title2': 'Just a Few Minutes',
    'landing.subtitle': 'Send invitations for your ceremonies (Wedding, Send-off, Confirmation, etc.) safely and easily via WhatsApp or SMS, track real-time attendance replies (RSVP), and verify guests at the door using custom QR Coordinates.',
    'landing.btnStart': 'Start Designing Event',
    'landing.btnHowItWorks': 'See How It Works',
    'landing.btnStartNow': 'Get Started Now',
    'landing.btnLogin': 'Login',
    'landing.inviteTag': 'Digital Invitation Cards Workspace',
    'landing.statSent': 'Cards Dispatched',
    'landing.statRsvped': 'Guests Replied RSVP',
    'landing.statSavePaper': 'Paper Saved & Ecology',
    'landing.featuresTitle': 'Outstanding Features',
    'landing.featuresHeading': 'All Guest Management Solutions in One Workspace',
    'landing.featuresSub': 'Say goodbye to printed invitation cards and wasteful expenses. EVENTCARD provides you with clean, modern digital technology.',
    'landing.howItWorksTitle': 'Simple & Human-Centered Steps',
    'landing.howItWorksHeading': 'Four Clear Steps to Power Your Special Day',
    'landing.howItWorksSub': 'Our platform is designed to offer maximum flexibility and ease of use. Here is the direct workflow from setup to event day.',
    'landing.faqTitle': 'Frequently Asked Questions (FAQs)',
    'landing.faqSub': 'We have answers to all common inquiries about our custom invitation platform.',
    'landing.tagline': 'Innovation, simplicity and absolute perfection of digital invitations in East Africa.',
    'landing.rights': 'EVENTCARD. All Rights Reserved. Crafted with high digital standards.',

    // Feature Cards
    'feature.1.title': '1. Modern Interactive Editor',
    'feature.1.desc': 'Select from presets or upload your own base image. You can intuitively drag and slide the coordinates of guest names, card badges, and secure QR Codes anywhere you prefer.',
    'feature.2.title': '2. Dispatch via WhatsApp & SMS',
    'feature.2.desc': 'Dispatch cards safely using highly engaging localized messaging. Guests receive personalized text templates with their own name and matching credentials.',
    'feature.3.title': '3. Real-Time Attendance Logs (RSVPs)',
    'feature.3.desc': 'Receive instant dashboard alerts as guests RSVP: "Attending", "Declined", or "Maybe". Simplify catering and seating planning effortlessly.',
    'feature.4.title': '4. Door Check-In (QR Scanner)',
    'feature.4.desc': 'On event day, door ushers scan the guests invitation QR using any phone browser camera. Block gate-crashers, invalid badges, or duplicate entries.',
    'feature.5.title': '5. Zero Paper Waste',
    'feature.5.desc': 'Be polite to nature, save trees! Guests appreciate receiving clean, high-resolution cards directly on their smartphones without losing them.',

    // Steps
    'step.1.title': 'Setup Event Coordinates',
    'step.1.desc': 'Input event type, venue hall name, maps coordinates, schedule dates, expected dress codes, and committee mobile numbers.',
    'step.2.title': 'Preview Text Templates',
    'step.2.desc': 'Inspect outbound SMS and WhatsApp message configurations. The billing steps have been entirely bypassed for direct access.',
    'step.3.title': 'Import Guest Lists',
    'step.3.desc': 'Add names manually or bulk paste your contact spreadsheet. Personalized cards with unique QR coordinates are instantly generated.',
    'step.4.title': 'Dispatch & Monitor RSVPs',
    'step.4.desc': 'Send invitations using SMS credit or WhatsApp, monitor responses, and scan RSVPs at the gate on event day.',

    // FAQ Content
    'faq.1.q': 'Do I need to wait for mobile SMS OTP verification to register?',
    'faq.1.a': 'No, for this specialized edition, we removed the OTP barrier. You can log in immediately by entering admin as username and admin as password.',
    'faq.2.q': 'Why is there no pricing or billing step displayed?',
    'faq.2.a': 'Great observation! The pricing and payment steps are entirely bypassed so you can try all card building features without billing obstacles.',
    'faq.3.q': 'How do guests fill out their RSVP replies?',
    'faq.3.a': 'Each guest receives a unique automated link in their message. Tapping it opens their personalized portal with their name, card type, and confirmation form.',

    // Admin Dashboard Info Panel
    'dash.welcome': 'Welcome to EVENTCARD Dashboard',
    'dash.intro': 'This is your complete guest and digital invitation console. The SMS OTP restriction has been removed. The pricing page has been bypassed. You can setup event details, preview message templates, choose presets, custom-align text fields, and dispatch invitations immediately.',
    'dash.btnCreateEvent': 'Set Up Event',
    'dash.statEventName': 'Active Event',
    'dash.statGuestsLoaded': 'Imported Cards',
    'dash.statRsvps': 'Confirmed RSVPs',
    'dash.statWallet': 'Prepaid Balance',
    'dash.workflowTitle': 'System Creation Workflow',
    'dash.wf1Title': '1. Event Details',
    'dash.wf1Desc': 'Fill in ceremony titles, dates, time, and dress code.',
    'dash.wf2Title': '2. Message Preview',
    'dash.wf2Desc': 'Verify SMS and WhatsApp message content (Billing is skipped).',
    'dash.wf3Title': '3. Align Card Templates',
    'dash.wf3Desc': 'Select color presets; adjust coordinates for names and QR codes.',
    'dash.wf4Title': '4. Import & Dispatch',
    'dash.wf4Desc': 'Add guests, dispatch cards, and scan barcodes on event day.',
    'dash.summaryCardTitle': 'Ceremony Summary Overview',
    'dash.summaryCardName': 'Ceremony Title:',
    'dash.summaryCardDateTime': 'Date & Time:',
    'dash.summaryCardHall': 'Venue Hall:',
    'dash.summaryCardHosts': 'Event Hosts:',
    'dash.summaryCardDress': 'Dress Code:',
    'dash.btnEditInfo': 'Edit Details',
    'dash.btnDesignCard': 'Design Template',

    // Event Details Form
    'form.title': 'Main Event Information Setup',
    'form.subtitle': 'Configure the core metadata of your ceremony. These details will construct your card templates and personalized messages.',
    'form.sec1': 'A: Sender Identity (Metadata)',
    'form.sec2': 'B: Dates and Hall Coordinates',
    'form.sec3': 'C: Hosts and Theme Attire',
    'form.sec4': 'D: RSVP Hotlines (Contacts)',
    'form.labelSender': 'SMS Sender Label ID',
    'form.labelEventName': 'Ceremony Title (e.g., WEDDING OF AMIN & ANNA)',
    'form.labelDate': 'Ceremony Date',
    'form.labelTime': 'Start Time',
    'form.labelPeriod': 'Period of Day',
    'form.labelHall': 'Venue Hall Name',
    'form.labelCoordinates': 'Location (Google Maps Lat, Lng)',
    'form.labelHosts': 'Main Hosts (e.g., Familia ya Rev. Fidelis & Partners)',
    'form.labelDress': 'Dress Theme / Color Code',
    'form.labelContact1': 'Comittee Hotline 1 (RSVP)',
    'form.labelContact2': 'Comittee Hotline 2 (RSVP)',
    'form.labelContact3': 'Comittee Hotline 3 (RSVP)',
    'form.labelEventCover': 'Event Cover Image',
    'form.labelSaveDateImg': 'Save the Date Image (Reminder)',
    'form.eventCoverHint': 'Upload a beautiful cover image for the guest invitation landing page.',
    'form.saveDateHint': 'Upload an image for "Save the Date" reminder messages.',
    'form.btnUpload': 'Upload Image',
    'form.btnChange': 'Change Image',
    'form.btnSave': 'Save Event Settings ✓',

    // Card Preview Page
    'preview.title': 'Review Invitation Notification Layouts',
    'preview.subtitle': 'The billing process has been completely bypassed! You can review the exact SMS and WhatsApp dispatch notifications received by guests.',
    'preview.smsTitle': 'A. Outbound SMS Text Notification Preview',
    'preview.whatsTitle': 'B. Outbound WhatsApp Rich Media Preview',
    'preview.priceAlert': 'Note: Pricing acts are bypassed. Proceed to card coordinate adjustment immediately.',
    'preview.btnNext': 'Go to Card Designer Tab',

    // Templates Selector
    'temp.title': 'Card Elements Layout Coordinate Settings',
    'temp.subtitle': 'Align text blocks, card types and QR coordinates beautifully on your template.',
    'temp.presetTitle': '1. Select Color Presets & Mood Layouts',
    'temp.positionTitle': '2. Component Alignments (Coordinates)',
    'temp.activeSection': 'Edit Section',
    'temp.tabName': 'Guest Name Placement',
    'temp.tabQr': 'QR Code Placement',
    'temp.tabType': 'Card Tag Badge',
    'temp.nameSliderHeader': 'Adjust Name Placement Coordinates',
    'temp.nameX': 'horizontal Align (Name X)',
    'temp.nameY': 'Vertical Align (Name Y)',
    'temp.nameSize': 'Typography Size',
    'temp.qrSliderHeader': 'Adjust QR Code Placement Coordinates',
    'temp.qrX': 'Horizontal Align (QR X)',
    'temp.qrY': 'Vertical Align (QR Y)',
    'temp.qrSize': 'Square Perimeter Size',
    'temp.typeSliderHeader': 'Adjust Card Type Label Coordinates',
    'temp.typeX': 'Horizontal Align (Label X)',
    'temp.typeY': 'Vertical Align (Label Y)',
    'temp.typeSize': 'Badge Font Size',
    'temp.textColorLabel': 'Typography Base Color',
    'temp.fontFamilyLabel': 'Aina ya Fonti (Font Family)',
    'temp.btnSave': 'Apply Element Coordinates ✓',
    'temp.btnSaved': 'Alignment Saved!',
    'temp.btnNext': 'Setup Guest Directoy',
    'temp.canvasHeader': '3. Template Canvas Workbench (450 x 600 px)',
    'temp.canvasSub': 'This is the exact layout guests will download as an image/PDF with their high-definition door scan coordinates.',

    // Upload Guests
    'guests.title': 'Import Guest Directory List',
    'guests.subtitle': 'Register your guests. The compiler instantly prepares a dynamic profile card with individual authentication barcodes.',
    'guests.formHeader': 'Add Individual Guest Profile',
    'guests.labelFullName': 'Full Corporate Guest Name',
    'guests.labelPhone': 'Active Phone Coordinate (e.g., 0714786751)',
    'guests.labelCardType': 'Seating Category (Badge Type)',
    'guests.btnAdd': 'Insert Guest to Directory +',
    'guests.bulkHeader': 'Bulk Import Guests (Excel Spreadsheet/Text Paste Simulator)',
    'guests.bulkDesc': 'Insert guest rows using the format "Full Name, Phone" separated by comma or tabs on new lines:',
    'guests.bulkPlaceholder': 'Example:\nGuest Name, Phone, Category\nFirst Guest Name, 0713111222, DOUBLE\nSecond Guest Name, 0755333444, SINGLE',
    'guests.btnBulk': 'Process Bulk Import List ✓',
    'guests.tableHeader': 'Registered Guest Directory',
    'guests.thName': 'Full Name',
    'guests.thPhone': 'Phone Coordinate',
    'guests.thCard': 'Tier Category',
    'guests.thStatus': 'Delivery Alert',
    'guests.thAction': 'Console UI',
    'guests.btnSms': 'Pending SMS',
    'guests.btnWhatsapp': 'Pending WhatsApp',
    'guests.btnDelete': 'Delete',
    'guests.noData': 'Your directory is currently empty. Insert individuals above to populate.',
    'guests.btnDemo': '',
    'guests.btnNext': 'Proceed to Delivery Workspace',

    // Send Messages
    'send.title': 'Message Delivery & Dispatch Logs',
    'send.subtitle': 'Dispatch cards safely to registered guests. Monitor cellular network delivery protocols securely on the registry below.',
    'send.btnSmsAll': 'Dispatch SMS to All Guests',
    'send.btnWhatsappAll': 'Dispatch WhatsApp to All Guests',
    'send.thName': 'Registered Name',
    'send.thPhone': 'Coordinates',
    'send.thSmsStatus': 'SMS Gateway',
    'send.thWhatStatus': 'WhatsApp API',
    'send.thActions': 'Single Dispatch Triggers',
    'send.noGuests': 'No registered guest records found to execute notification dispatch workflows.',
    'send.smsStatusOk': 'Delivered',
    'send.smsStatusSending': 'Sending',
    'send.smsStatusPending': 'Pending',
    'send.btnSmsSingle': 'Dispatch SMS',
    'send.btnWhatSingle': 'Dispatch WhatsApp',
    'send.btnNext': 'Open RSVP Response Tracker',

    // RSVP Responses
    'rsvp.title': 'Real-Time RSVP Tracker Logs',
    'rsvp.subtitle': 'Analyze ceremony projections, confirmed attendance heads, and guest remarks.',
    'rsvp.btnDemo': 'Simulate Guest Submissions (Demo Click)',
    'rsvp.statAttending': 'Attending (Heads)',
    'rsvp.statDeclined': 'Declined (Cards)',
    'rsvp.statMaybe': 'Not Confirmed',
    'rsvp.statPending': 'No Reply Yet',
    'rsvp.chartTitle': 'RSVP Attendance Distribution (Analytics)',
    'rsvp.chartAttending': 'ATTENDING GUESTS',
    'rsvp.chartDeclined': 'DECLINED INVITATIONS',
    'rsvp.chartPending': 'PENDING OUTCOMES',
    'rsvp.tableTitle': 'Guest Name',
    'rsvp.thPhone': 'Phone',
    'rsvp.thStatus': 'RSVP Status',
    'rsvp.thCount': 'Attending Seats',
    'rsvp.thComment': 'Remarks & Well Wishes',
    'rsvp.thActions': 'Interactive Console',
    'rsvp.btnSim': 'Woven Simulator (RSVP)',
    'rsvp.noGuests': 'No guest lists loaded to monitor ceremony RSVPs.',
    'rsvp.btnNext': 'Open Gate QR Verification',

    // RSVP Guest Simulator Dialog
    'sim.badge': 'Woven Simulation: Guest Browser Mockup viewport',
    'sim.webTitle': 'PERSONALIZED GATEWAY PORTAL (RSVP LOGS UNIT)',
    'sim.welcomeMsg': 'You are invited! Confirm your ceremony attendance below.',
    'sim.qAttendance': 'Will you attend our special ceremony?',
    'sim.btnAttending': '✓ I Will Come',
    'sim.btnDeclined': '✕ Cannot Come',
    'sim.btnMaybe': '? Uncertain',
    'sim.qCompanions': 'How many companions are you coming with (Seating Reservation)?',
    'sim.opt1': 'Just Myself (1 Reserved Seat)',
    'sim.opt2': 'With my Partner (2 Reserved Seats)',
    'sim.opt3': 'Three heads (3 Reserved Seats)',
    'sim.qComment': 'Send Your Well Wishes & Warm Words to the Host',
    'sim.commentPlaceholder': 'e.g., Congratulations! Looking forward to celebrating with you!',
    'sim.btnSubmit': 'Submit RSVP Response ✓',

    // QR Check-in
    'scan.title': 'Gate QR Scanner & Security Verification',
    'scan.subtitle': 'Verify invitation codes at the entrance to prevent fraud, multiple entries, or gate-crashing.',
    'scan.tabQr': 'Camera QR Viewfinder',
    'scan.tabList': 'Checked-In Logbook',
    'scan.scannerActive': 'GATE MONITOR SCANNER INTERACTIVE',
    'scan.waiting': 'Awaiting invitation scan...',
    'scan.scanOkTitle': 'Credential Verified!',
    'scan.scanDupTitle': 'Badge Already Claimed!',
    'scan.scanWarn': '*Warning: This QR holds an active check-in timestamp!',
    'scan.scanFailTitle': 'Invalid Invitation Code!',
    'scan.scanFailText': 'The scanned security token was not found in our directory or holds an invalid checksum.',
    'scan.simBoxTitle': 'Gate Check-In Simulation Utilities',
    'scan.simBoxDesc': 'Select a guest from the registry dropdown below, and trigger "Complete Scan" to simulate barcode scans at the entrance.',
    'scan.dropdownLabel': 'Select Guest to Simulate Scan',
    'scan.btnSubmit': 'Complete Security Scan',
    'scan.statChecked': 'Inside Venue',
    'scan.statRsvped': 'Rsvped Attendees',
    'scan.tblHeader': 'Gate Entrance Logs',
    'scan.thName': 'Verified Guest',
    'scan.thPhone': 'Mobile',
    'scan.thCard': 'Entrance Category',
    'scan.thTime': 'Entrance Timestamp',
    'scan.thVerify': 'Gate Status',
    'scan.noCheckedIn': 'No attendees checked in yet. Start scanning badges to populate gate registry.',

    // Settings Form
    'sett.title': 'Administrator Profile Settings',
    'sett.labelName': 'Full Executive Name',
    'sett.labelEmail': 'Control Email Address',
    'sett.labelPhone': 'Primary Mobile Contact',
    'sett.labelFont': 'System-wide Font Selection',
    'sett.fontDesc': 'Change the typography styling for the entire EVENTCARD framework. Updates apply instantly system-wide.',
    'sett.btnSave': 'Save Workspace Profile ✓',
    'sett.alertSaved': 'Control details updated!',

    // Wallet Page
    'wallet.title': 'Prepaid Gateway Wallet',
    'wallet.typePrepaid': 'EVENTCARD PREPAID WORKSPACE',
    'wallet.totalBal': 'Available Balance',
    'wallet.tagActive': 'Active',
    'wallet.tagUnlimited': 'Access: Unlimited',
    'wallet.rechargeTitle': 'Prepaid Recharge Simulator',
    'wallet.rechargeDesc': 'Simulate depositing TZS balance to handle imaginary SMS bundles seamlessly here.',
    'wallet.rechargeSelect': 'Select Simulated Amont',
    'wallet.btnRecharge': 'Process simulated Top-Up',
    'wallet.rechargeSuccess': 'credited to your virtual wallet for simulation!',
    'wallet.tblHistory': 'Workspace Transaction Registry',
    'wallet.thDate': 'Timestamp',
    'wallet.thDesc': 'Workflow details',
    'wallet.thType': 'Class Code',
    'wallet.thAmount': 'Amount',
    'wallet.typeIn': 'CREDIT',
    'wallet.typeOut': 'DEBIT',
    'wallet.depositDesc': 'Simulated Deposit AirtelMoney',
    'wallet.purchaseDesc': 'SMS Pack Purchase (1000 SMS)',

    // Login page
    'login.title': 'Secure Administrator Sign-In',
    'login.sub': 'EVENTCARD Digital Invitation Control Panel',
    'login.note': 'Security Bypass: Type admin as username and admin as password to bypass active OTP tests.',
    'login.username': 'Username Coordinates',
    'login.password': 'Security Password',
    'login.btnSubmit': 'Access Terminal Securely ✓',
    'login.btnBack': '← Return to Portal',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = safeLocalStorage.getItem('kadi_language');
    return (saved as Language) || 'sw';
  });

  useEffect(() => {
    safeLocalStorage.setItem('kadi_language', language);
  }, [language]);

  const t = (key: TranslationKey, fallback?: string): string => {
    const section = TRANSLATIONS[language];
    if (section && section[key]) {
      return section[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
